### ISSUE TITLE
DOCKER <error> You must set the ADDRESS environment variable.

### ISSUE THREAD

**Issue by pejix** [ottomated/CrewLink-server#117]
<error> You must set the ADDRESS environment variable.

Any idea how to fix this? 
I'm running docker.

**Comment by lorenzwinkler1** [comment]
Apperantly you must specify the environment variable "ADDRESS" when starting

with for example -e ADDRESS=YOUR_ADRESS
when using "run"

Unfortunately i do not have a clue what that adress should be. I tried it using my IP, localhost, but nothing did work. Should be covered in the docs

**Comment by gauravspatel** [comment]
http://[your-ip-here]:[your-port] or https:// if you're using SSL

**Comment by lorenzwinkler1** [comment]
ADDRESS=http://[myip]:9736
                        ^

SyntaxError: Unexpected token ':'
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_string.js:23:3

**Comment by lorenzwinkler1** [comment]
Using the command
docker run -p 9736:9736 ottomated/crewlink-server:latest -e ADDRESS=http://[ip]:9736

**Comment by pejix** [comment]
Thanks!

**Comment by pejix** [comment]
[eval]:1
ADDRESS=http://78.67.xx.xx:9736
            ^

SyntaxError: Unexpected token ':'
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_string.js:23:3
[eval]:1
ADDRESS=http://78.67.232.143:9736
            ^

SyntaxError: Unexpected token ':'
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_string.js:23:3

**Comment by pejix** [comment]
ADDRESS=http://78.67.xx.xx:9736
^

SyntaxError: Unexpected token ':'
at new Script (vm.js:101:7)
at createScript (vm.js:262:10)
at Object.runInThisContext (vm.js:310:10)
at internal/process/execution.js:77:19
at eval-wrapper:6:22
at evalScript (internal/process/execution.js:76:60)
at internal/main/eval_string.js:23:3
eval:1
ADDRESS=http://78.67.xx.xx:9736
^

SyntaxError: Unexpected token ':'
at new Script (vm.js:101:7)
at createScript (vm.js:262:10)
at Object.runInThisContext (vm.js:310:10)
at internal/process/execution.js:77:19
at eval-wrapper:6:22
at evalScript (internal/process/execution.js:76:60)
at internal/main/eval_string.js:23:3

**Comment by Dragonfreaky** [comment]
I got this issue as well, even tho I run through NodeJS + Yarn.
I couldn't for the life of me figure out how to set it without adding additional modules or such..

So I just hardcoded it in the src\index.ts file.
line: 49
Replace `var address = process.env.ADDRESS;` with `var address = process.env.ADDRESS || '9736';`

So pretty much added the port number as an optional value.

Hopefully it's helpful, looking forward to a better solution.

**Comment by joshuaho96** [comment]
This is a dupe of this issue: https://github.com/ottomated/CrewLink-server/issues/116

**Comment by MoSadie** [comment]
@lorenzwinkler1 and @pejix your issue is probably because you have the -e argument at the end, try putting it before the ```ottomated/crewlink-server:latest``` part. Any argument after the image is passed to the container as a command to run in that container.

Ex: ```docker run -e ADDRESS='http://your.ip.or.domain.here' -d -p 9736:9736 ottomated/crewlink-server:latest```

**Comment by joshuaho96** [comment]
If this is intended behavior can we get an update in the readme to note this?

**Comment by pejix** [comment]
> 
> 
> @lorenzwinkler1 and @pejix your issue is probably because you have the -e argument at the end, try putting it before the `ottomated/crewlink-server:latest` part. Any argument after the image is passed to the container as a command to run in that container.
> 
> Ex: `docker run -e ADDRESS='http://your.ip.or.domain.here' -d -p 9736:9736 ottomated/crewlink-server:latest`

THANKS SIR!

**Comment by popeter45** [comment]
the ADDRESS variable works on my docker desktop instance but when i try on my synologoy diskstation the docker runs but cant connect to the server at all

**Comment by Zedifuu** [comment]
> ADDRESS=http://78.67.xx.xx:9736
> ^
> 
> SyntaxError: Unexpected token ':'
> at new Script (vm.js:101:7)
> at createScript (vm.js:262:10)
> at Object.runInThisContext (vm.js:310:10)
> at internal/process/execution.js:77:19
> at eval-wrapper:6:22
> at evalScript (internal/process/execution.js:76:60)
> at internal/main/eval_string.js:23:3
> eval:1
> ADDRESS=http://78.67.xx.xx:9736
> ^
> 
> SyntaxError: Unexpected token ':'
> at new Script (vm.js:101:7)
> at createScript (vm.js:262:10)
> at Object.runInThisContext (vm.js:310:10)
> at internal/process/execution.js:77:19
> at eval-wrapper:6:22
> at evalScript (internal/process/execution.js:76:60)
> at internal/main/eval_string.js:23:3

###  ADDRESS="http://78.67.xx.xx:9736"
 
 Make it a string, else it no gonna work. **" "**
 
 
 Also if you're using docker, I'd really recommend **docker-compose**. 
 I speak about it over here: https://github.com/ottomated/CrewLink-server/issues/165#issuecomment-771194903
