### ISSUE TITLE
HTTPS is not working for me (Heroku)

### ISSUE THREAD

**Issue by ForgenDT** [ottomated/CrewLink-server#150]
hello,
as written in the title, the https does not work, yet I followed the instructions...
An idea ?

environment variable : OK

`2021-01-10T18:03:35.711790+00:00 app[web.1]: Error: ENOENT: no such file or directory, open '/app/privkey.pem'
2021-01-10T18:03:35.711791+00:00 app[web.1]:     at Object.openSync (fs.js:462:3)
2021-01-10T18:03:35.711791+00:00 app[web.1]:     at Object.readFileSync (fs.js:364:35)
2021-01-10T18:03:35.711792+00:00 app[web.1]:     at Object.<anonymous> (/app/dist/index.js:61:19)
2021-01-10T18:03:35.711792+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-01-10T18:03:35.711793+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-01-10T18:03:35.711793+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-01-10T18:03:35.711794+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-01-10T18:03:35.711794+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
2021-01-10T18:03:35.711795+00:00 app[web.1]:     at internal/main/run_main_module.js:17:47 {
2021-01-10T18:03:35.711795+00:00 app[web.1]:   errno: -2,
2021-01-10T18:03:35.711795+00:00 app[web.1]:   syscall: 'open',
2021-01-10T18:03:35.711796+00:00 app[web.1]:   code: 'ENOENT',
2021-01-10T18:03:35.711796+00:00 app[web.1]:   path: '/app/privkey.pem'
2021-01-10T18:03:35.711797+00:00 app[web.1]: }`

**Comment by ScarVite** [comment]
this most likely means, that your privkey is sitting inside the wrong directory

**Comment by ForgenDT** [comment]
the problem is that I don't know where the privkey is. heroku does not give information.

**Comment by ScarVite** [comment]
you Need to create your own, you create one usinge LetsEncrypt.

You need the cert for your domain

**Comment by ForgenDT** [comment]
it works 👍
